#!/bin/bash

if [ -z "$1" ]; then
  echo ERROR: Enter your client name as the first argument.
  exit 1
fi

# Create a certificate with the given client name
# Asks for a use password and the CA root key password
docker-compose run --rm openvpn easyrsa build-client-full "$1"
