#!/bin/bash

if [ -z "$1" ]; then
  echo ERROR: Enter your FQDN VPN domain as the first argument.
  exit 1
fi

if [ -d "./openvpn-data" ]; then
  echo WARNING: Server has already been initialised.
fi

# Initialises OpenVPN server configuration files
# Use on another devive when storing the CA root key separately (recommended)
# Use on the server device when storing the CA root key on the VPN server (not recommended)

# This process will ask for the same root CA password throughout
docker-compose run --rm openvpn ovpn_genconfig -u udp://"$1" && \
docker-compose run --rm openvpn ovpn_initpki && \

# Fixes file ownership issue encountered when copying files
sudo chown -R $(whoami): ./openvpn-data-ca
