#!/bin/bash

# Interactive Menu Managing an OpenVPN Docker Container
# Supports CA Root and Server File Separation

# Maintained by Maksim Stojkovic - https://github.com/silentdigit

main_menu() {
  while true; do
    clear

    echo "Main Menu:"
    print_menu "${main_opts[@]}"
    echo

    read -n 1 -p "Please enter your choice: " RESPONSE && \
      echo && [ "$RESPONSE" != $'\n' ] && echo

    case ${RESPONSE} in
      "0")
        # Quit
        clear
        return;;
      "1")
        # Start server
        start_server
        wait_input;;
      "2")
        # Stop server
        stop_server
        wait_input;;
      "3")
        # Restart server
        restart_server
        wait_input;;
      "4")
        # Remove server container
        remove_server
#        docker stop ${SERVER_NAME} && docker rm ${SERVER_NAME}
        wait_input;;
      "5")
        # Manage server
        management_menu;;
      *)
        echo "Invalid option. Try again."
        wait_input;;
    esac
  done
}

start_server() {

  # Initialise CA before starting server
  [ ! -d "$CA_DIR" ] && echo "ERROR: Initialise server before proceeding" && return 1

  # Exit if server already started
  container_running $SERVER_NAME && echo "VPN server already running" && return 0

  # Generate server files before starting if CA exists
  [ -d "$CA_DIR" ] && echo "Updating VPN server files" && gen_files && \

  # Start server if it exists, otherwise run a new server container
  echo "Starting VPN server" && \
  container_exists $SERVER_NAME && docker start $SERVER_NAME || docker run $SERVER_PARAMS
  return 0
}

stop_server() {
  # Return if server container does not exist
  ! container_exists $SERVER_NAME && echo "ERROR: No VPN server container exists" && return 1

  # Stop server if container is running
  container_running $SERVER_NAME && echo "Stopping VPN server" && docker stop $SERVER_NAME || echo "VPN server already stopped"
  return 0
}

restart_server() {
  # Return if server container does not exist
  ! container_exists $SERVER_NAME && echo "ERROR: No VPN server container exists" && return 1

  # Return if server not currently running
  ! container_running $SERVER_NAME && echo "VPN server not currently running" && return 0

  # Restart server if container is running
  echo "Restarting VPN server" && docker restart $SERVER_NAME
  return 0
}

remove_server() {
  # Removing stopped server container
  stop_server && echo "Removing VPN server container" && docker rm $SERVER_NAME
  return 0
}

management_menu() {
  while true; do
    clear

    echo "Server Management:"
    print_menu "${manage_opts[@]}"
    echo

    read -n 1 -p "Please enter your choice: " RESPONSE && \
      echo && [ "$RESPONSE" != $'\n' ] && echo

    case ${RESPONSE} in
      "0")
        # Return to main menu
        clear
        return;;
      "1")
        # List user certificates
        echo "User Certificates:"
        list_user
        wait_input;;
      "2")
        # Create user certificate
        echo "Creating user certificate"
        create_user
        wait_input;;
      "3")
        # Get user certificate
        echo "Getting user certificate"
        get_user
        wait_input;;
      "4")
        # Revoke user certificate
        echo "Revoking user certificate"
        revoke_user
        wait_input;;
      "5")
        # Remove user certificate
        echo "Removing user certificate"
        remove_user
        wait_input;;
      "6")
        # Initialise server
        echo "Initialising VPN server"
        init_server
        wait_input;;
      "7")
        # Generate server files
        echo "Generating VPN server files"
        gen_files
        wait_input;;
      *)
        echo "Invalid option. Try again."
        wait_input;;
    esac
  done
}

init_server() {
  echo "You will be asked to enter you VPN FQDN, common name and CA root key password (password required multiple times)"
  echo "Ensure that your CA root key password is long and secure"

  read -rp "VPN FQDN (domain): " VPN_DOMAIN
  VPN_DOMAIN=$(echo ${VPN_DOMAIN} | awk '{print tolower($0)}')
  docker run ${CA_PARAMS} ovpn_genconfig -u udp://${VPN_DOMAIN}
  docker run ${CA_PARAMS} ovpn_initpki
}

gen_files() {
  docker run ${CA_PARAMS} ovpn_copy_server_files
  rm -rf ${SERVER_DIR}
  mv -f ${CA_DIR}/server ${SERVER_DIR}
  echo "Server files can be found at '${SERVER_DIR}'"
}

list_user() {
  DOMAIN=$(head -n 1 openvpn-data-ca/pki/index.txt)
  DOMAIN=${DOMAIN#*CN=}

  ls -I ${DOMAIN}.crt --width=12 openvpn-data-ca/pki/issued | sed 's|\.crt||g'
}

create_user() {
  read -rp "Username: " CLIENTNAME
  docker run ${CA_PARAMS} easyrsa build-client-full ${CLIENTNAME}
}

get_user() {
  read -rp "Username: " CLIENTNAME
  mkdir -p ${CLIENT_DIR}
  docker run ${CA_PARAMS} ovpn_getclient ${CLIENTNAME} > ${CLIENT_DIR}/${CLIENTNAME}.ovpn
}

revoke_user() {
  read -rp "Username: " CLIENTNAME
  docker run ${CA_PARAMS} ovpn_revokeclient ${CLIENTNAME}
}

remove_user() {
  read -rp "Username: " CLIENTNAME
  docker run ${CA_PARAMS} ovpn_revokeclient ${CLIENTNAME} remove
}

wait_input() {
  echo -e "\nPress ENTER to Continue"
  read -n 1 -s
}

print_menu() {
  if [ -z "$1" ]; then
    exit 1
  fi

  arr=("$@")
  for i in ${!arr[@]}; do
    [ "$i" -lt "$((${#arr[@]} - 1))" ] && echo "$((${i} + 1))) ${arr[${i}]}" || echo "0) ${arr[${i}]}"
  done
}

container_exists() {
  # Exit if no container passed
  [ -z "$1" ] && exit 1

  # Return 0 if inspect returns successfully
  docker container inspect "$1" > /dev/null 2>&1 && return 0 || return 1
}

container_running() {
  # Exit if no container name passed
  [ -z "$1" ] && exit 1

  [ "$(docker inspect -f '{{.State.Running}}' "$1" 2>/dev/null)" = "true" ] && return 0 || return 1
}

# Variables
main_opts=("Start Server" "Stop Server" "Restart Server" "Remove Server Container" "Manage Server" "Quit")
manage_opts=("List User Certificates" "Create User Certificate" "Get User Certificate" "Revoke User Certificate" "Remove User Certificate" "Initialise Server" "Generate Server Files" "Return to Main Menu")

DOCKER_IMAGE="silentdigit/openvpn"
CA_NAME="openvpn_ca"
SERVER_NAME="openvpn_server"

CLIENT_DIR="${PWD}/clients"

if [ -z "$CA_DIR" ]; then
  export CA_DIR=${PWD}/openvpn-data-ca
fi

if [ -z "$SERVER_DIR" ]; then
  export SERVER_DIR=${PWD}/openvpn-data-server
fi

CA_PARAMS=" -it --rm --name ${CA_NAME} -v ${CA_DIR}:/etc/openvpn --log-driver=none ${DOCKER_IMAGE}"
SERVER_PARAMS="-d --name ${SERVER_NAME} -v ${SERVER_DIR}:/etc/openvpn -p 1194:1194/udp --cap-add=NET_ADMIN ${DOCKER_IMAGE}"

# Start main menu
main_menu
